/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ResultsPage.module.css";
import ResultCard from "./ResultCard";

const resultsData = [
  { name: "Hotel Fiu Fiu", address: "Campana 4100", price: "600" },
  { name: "Nombre", address: "Direccion", price: "" },
  { name: "Nombre", address: "Direccion", price: "" },
  { name: "Nombre", address: "Direccion", price: "" },
  { name: "Nombre", address: "Direccion", price: "" },
  { name: "Nombre", address: "Direccion", price: "" },
];

const ResultsPage = () => {
  return (
    <main className={styles.resultsContainer}>
      <h1 className={styles.pageTitle}>Resultados Tandil</h1>
      <section className={styles.cardGrid}>
        {resultsData.map((result, index) => (
          <ResultCard
            key={index}
            name={result.name}
            address={result.address}
            price={result.price}
          />
        ))}
      </section>
    </main>
  );
};

export default ResultsPage;
