# -*- coding: utf-8 -*-
"""Top Gun - Commision 3 - Ollama y Prompt Largos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1653pxsoNijJZjkntadFMzUEfYnfIidaE
"""

!curl -fsSL https://ollama.com/install.sh | sh

!ollama --version

# Commented out IPython magic to ensure Python compatibility.
!pip install colab-xterm #https://pypi.org/project/colab-xterm/
# %load_ext colabxterm

# Commented out IPython magic to ensure Python compatibility.
# %xterm

!ollama pull llama3.2

!ollama run llama3.2 "Hola que tal"

!pip install gradio ollama

import gradio as gr
import ollama

def chat(message):
  response = ollama.chat(model='llama3.2', messages=[
    {
      'role': 'user',
      'content': message,
    },
  ])
  return response['message']['content']


iface = gr.Interface(fn=chat, inputs="text", outputs="text")
iface.launch()

!pip install langchain langchain_ollama

from langchain_ollama import OllamaLLM
from langchain_core.prompts import ChatPromptTemplate

model = OllamaLLM(model="llama3.2")

def resumir_con_ollama(chunks):
    template = (
      "Resumine este texto en 40 palabras: {texto}. "
    )

    prompt = ChatPromptTemplate.from_template(template)
    chain = prompt | model

    parsed_results = []

    for i, chunk in enumerate(chunks, start=1):
        response = chain.invoke(
            {"texto": chunk }
        )
        print(f"Parsed batch: {i} of {len(chunks)}")
        parsed_results.append(response)

    return "\n".join(parsed_results)

def read_chunks(text_file, size=6000):
    chunks = []


    with open(text_file, 'r', encoding='utf-8') as file:
    #with open(text_file, 'r', encoding='cp1252') as file:
        while True:
            # Leer 'size' caracteres del archivo
            chunk = file.read(size)

            # Si no hay más texto que leer, terminar el bucle
            if not chunk:
                break

            # Agregar el fragmento a la lista de chunks
            chunks.append(chunk)

    return chunks

chunks = read_chunks("alquimista.txt")
result = resumir_con_ollama(chunks)
print(result)