/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./TodoList.module.css";

const TaskItem = ({ text }) => {
  return (
    <div className={styles.taskItem}>
      <div className={styles.taskContent}>
        <div
          className={styles.checkbox}
          role="checkbox"
          tabIndex="0"
          aria-checked="false"
        />
        <div>{text}</div>
      </div>
      <button className={styles.deleteButton}>borrar</button>
    </div>
  );
};

export default TaskItem;
