/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MyComponent.module.css";

const MainPanel = () => (
  <section className={styles.mainPanelContent}>
    <header className={styles.welcomeSection}>
      {" "}
      Bienvendios a mi Aplicacion{" "}
    </header>
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/b5495d6b7bbcd878cf72ed171005ca7d3a7dd7e0f2b61297bf68cb03dba2726c?apiKey=22faa001a5e944e1af9245bac93bdd4d&&apiKey=22faa001a5e944e1af9245bac93bdd4d"
      className={styles.image}
      alt="Main visual display"
    />
  </section>
);

export default MainPanel;
