/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MyComponent.module.css";
import MainContent from "./structure/MainContent";

function MyComponent() {
  return (
    <div className={styles.container}>
      <MainContent />
    </div>
  );
}

export default MyComponent;
