# -*- coding: utf-8 -*-
"""Dev10X - Ejemplo Uso de Gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16c1wPRxKysDTzKWZsVqaXV7lPzBRF7hK
"""

!pip install gradio

!pip install groq

import gradio as gr
from groq import Groq


def procesar_prompt(prompt):
    #ACa puede llamar a Olama, llamar a Groq o openai con la api key, consutlrar una base de datos RAG
    client = Groq(api_key = "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")
    respuesta = client.chat.completions.create(
        model="llama3-70b-8192",
        messages=[
            {"role": "system", "content": "Eres un asistente comediante que todo lo responde en forma graciosa y con chistes"},
            {"role": "user", "content": prompt}
        ]
    )
    return respuesta.choices[0].message.content

iface = gr.Interface(fn=procesar_prompt, inputs="text", outputs="text")
iface.launch()