/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "../MyComponent.module.css";
import Navigation from "../Navigation";
import MainPanel from "../MainPanel";

const MainContent = () => (
  <div className={styles.mainContent}>
    <aside className={styles.sidebar}>
      <Navigation />
    </aside>
    <main className={styles.mainPanel}>
      <MainPanel />
    </main>
  </div>
);

export default MainContent;
