/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MyComponent.module.css";

const Navigation = () => (
  <nav className={styles.navWrapper}>
    <div className={styles.navItem}>Menu de Navegacion</div>
    <button className={styles.navButton}>Menu 1</button>
    <button className={styles.navButton}>Menu 2</button>
    <button className={styles.navButton}>Menu 3</button>
  </nav>
);

export default Navigation;
